# Generated by Django 3.2 on 2023-12-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsyetem', '0002_comment1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
